[package]
name = "example-gtk4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.gtk]
package = "gtk4"
version = "0.4"


[dependencies.relm4]
version = "0.4"
features = ["macros"]
