[package]
name = "example-rust-gtk4"
version = "0.1.0"
edition = "2021"

[lib]
name = "gauges"
crate-type = ["lib", "cdylib"]

[dependencies.gtk]
package = "gtk4"
version = "0.4"


[dependencies.relm4]
version = "0.4"
features = ["macros"]
